[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/docker-entrypoint.sh"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[services]]
name = "castor"

[services.variables]
PORT = "5000"
LEDGER_MODE = "mock"
